### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Anaminus** [RobloxAPI/rbxfile#1]
- rbxfile
  - [ ] Add package documentation (usage).
  - [x] Consider Roblox-like API for rbxfile.Instance for more familiar manipulation.
    - Also makes RobloxCodec implementation easier.
  - [x] Merge rbxtype back into rbxfile.
  - [x] ValueReference points to a real Instance rather than being a reference string.
- ~~rbxfile/command~~ rbxplore
  - An executable used for binary `<->` xml conversion.
  - Figure out release builds on github.
- rbxfile/bin
  - [x] Implement format model deserializer.
    - [x] Use ValueReference to read ref arrays in Instance and Parent chunks.
  - [x] Implement format model serializer.
  - [ ] Ideally, lz4 compressor should produce data that is binary-equal to data produced by Roblox's compressor.
  - ~~Should short CFrames be implemented by the format or the codec?~~ Codec
  - [x] Implement RobloxCodec.
    - [x] Option to ignore items that are invalid according to an API dump.
    - [x] Emulate Roblox decoding behavior.
      - Generate structures as chunks are read.
      - [x] Special CFrames.
    - [x] Emulate Roblox encoding behavior.
      - Single Instance chunk per class.
      - Single Property chunk per property per instance group.
        - Order by group ID, then property name.
      - Single Parent chunk.
      - To favor directness of decoding behavior, write Instance chunks first, then Property chunks, then Parent chunk.
      - End chunk whose content is `</roblox>`.
      - [x] Special CFrames.
      - [x] Warnings.
    - [x] Option to use API dump to properly decode ambiguous types (e.g. string vs BinaryString).
      - With API:
        - The correct in-memory representation can be determined from property and class name, making encoding to another format more correct.
        - Figure out bin.Value -> rbxfile.Value transform.
      - Wihout API:
        - A default will be chosen and used for the memory representation, which may become incorrect when encoding to another format.
        - Use a default rbxfile.Value for given bin.Value.
      - Shouldn't make a difference when encoding back into the same format.
  - Implement remaining value formats.
    - [x] ColorSequence
    - [x] ColorSequenceKeypoint
    - [x] NumberRange
    - [x] NumberSequence
    - [x] NumberSequenceKeypoint
    - [x] Axes
    - [x] BrickColor
    - [x] Color3
    - [x] Vector2
      - [x] Verify some crap in the spec about scaling.
        - "When converted float values to a scale of 0-255, values appear to always round down."
        - Might be a Color3 thing put in the wrong section.
    - [x] Vector3
    - [x] CFrame
      - [x] Short variation
      - [x] Full variation
    - [x] Token
    - [x] Referent
    - [x] Vector3int16 (0x14)
    - Unknown formats:
      - [x] UDim (0x6)
        - [x] Stub
      - [x] Vector2int16 (0xF)
        - [x] Stub
      - [x] CFrameQuat (0x11)
        - [x] Stub
    - [x] ~~Maybe change fielded types to arrays, which may be easier to convert.~~ Added "fielder" interface.
    - [x] Improve verbosity of nested errors.
  - Things to check:
    - [x] FormatModel.GroupCount vs number of actual groups.
    - [x] FormatModel.InstanceCount vs number of actual instances.
    - [x] Whether ChunkInstance.GetService indicates if the instance is a service, or if it's simply a child of the DataModel.
    - [x] Repeated GroupIDs.
    - [x] Repeated InstanceIDs.
    - [x] Order of chunk types.
    - [x] How format is decoded.
    - [x] Length of ChunkParent.Children/Parent matches InstanceCount.
    - [x] If instances in ChunkParent actually exist.
    - [x] How properties of ChunkProperty not in type of specified instance group are handled.
    - [x] Compatibility of properties and datatypes when given API vs no API.
    - [x] Length of ChunkProperty.Properties vs length of ChunkInstance.InstanceIDs.
    - [x] How client determines binary vs XML.
    - [x] Determine actual binary header magic (ErrCorruptHeader should be used somewhere).
    - [x] ~~Whether length of value-array bytes must be divisible by value size (are non-divisible bytes of last value ignored or errored).~~ Ignored
    - [x] The results of unspecified values of short CFrames (defaults or ~~errors~~).
    - [x] If TypeID is signed.
    - [x] ~~Is binary representation of UDim.Offset int16 or int32.~~ In-memory is int16, while it is encoded as int32.
- [x] Implement some kind of json format.
  - Simple reflection of Root structure is probably best.
- ~~Implement Terrain format.~~ Out of scope
- [ ] Unit tests on everything.
- [x] ~~Make everything threadsafe (abs(hell)).~~

**Comment by Anaminus** [comment]
This is mostly finished. Any unfinished tasks can be added as separate issues.
