### ISSUE TITLE
TODO: XML

### ISSUE THREAD

**Issue by Anaminus** [RobloxAPI/rbxfile#2]
- [x] Lenient start-tag parsing.
  - Instead of halting entire parser, ignore data up to corresponding end-tag.
- [x] Remove unused/unnecessary distinction between RBXLX and RBXMX.
- [ ] Make sure number returned from Document.ReadFrom/WriteTo is correct.
- [x] Write serializer.
  - [x] Use rbxdump to determine property types.
    - With API: The value type will be determined by the property and class name.
    - Without API: The type will be guessed based on the tag name, which is not reliable.
- [x] Option to ignore items that are invalid according to an API dump.
- [x] Warnings
- [ ] Unit tests on everything.
- [x] ~~Make everything threadsafe.~~

**Comment by Anaminus** [comment]
This is mostly finished. Any unfinished tasks can be added as separate issues.
